### ISSUE TITLE
Kopf ServerDisconnectedError without restart

### ISSUE THREAD

**Issue by jkupferer** [redhat-cop/anarchy#82]
```
[2020-07-01 16:20:56,486] kopf.reactor.running [ERROR   ] Root task 'watcher of anarchyruns.anarchy.gpte.redhat.com' is failed: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kopf/reactor/running.py", line 453, in _root_task_checker
    await coro
  File "/usr/local/lib/python3.8/site-packages/kopf/reactor/queueing.py", line 109, in watcher
    async for raw_event in stream:
  File "/usr/local/lib/python3.8/site-packages/kopf/clients/watching.py", line 75, in infinite_watch
    async for raw_event in stream:
  File "/usr/local/lib/python3.8/site-packages/kopf/clients/watching.py", line 112, in streaming_watch
    async for raw_event in stream:
  File "/usr/local/lib/python3.8/site-packages/kopf/clients/watching.py", line 146, in continuous_watch
    async for raw_input in stream:
  File "/usr/local/lib/python3.8/site-packages/kopf/clients/auth.py", line 78, in wrapper
    async for item in fn(*args, **kwargs, context=context):
  File "/usr/local/lib/python3.8/site-packages/kopf/clients/watching.py", line 211, in watch_objs
    response = await context.session.get(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError
```

**Comment by jkupferer** [comment]
Fixed
