### ISSUE TITLE
Anarchy error when 404 when attempting to delete AnarchyRun

### ISSUE THREAD

**Issue by jkupferer** [redhat-cop/anarchy#86]
```
Traceback (most recent call last):
  File "operator.py", line 528, in main_loop
    AnarchyGovernor.cleanup(runtime)
  File "/opt/app-root/operator/anarchygovernor.py", line 89, in cleanup
    governor.cleanup_runs(runtime)
  File "/opt/app-root/operator/anarchygovernor.py", line 298, in cleanup_runs
    runtime.custom_objects_api.delete_namespaced_custom_object(
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api/custom_objects_api.py", line 454, in delete_namespaced_custom_object
    (data) = self.delete_namespaced_custom_object_with_http_info(group, version, namespace, plural, name, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api/custom_objects_api.py", line 555, in delete_namespaced_custom_object_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 340, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 172, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 406, in request
    return self.rest_client.DELETE(url,
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 263, in DELETE
    return self.request("DELETE", url,
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 231, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '6a374d8b-295c-49fe-b466-d50cf07e628d', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 14 Jul 2020 17:06:29 GMT', 'Content-Length': '366'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"anarchyruns.anarchy.gpte.redhat.com \"sandboxes.rhs-2020-service-mesh.test-gkxxd-provision-ntp2stzwhd\" not found","reason":"NotFound","details":{"name":"sandboxes.rhs-2020-service-mesh.test-gkxxd-provision-ntp2stzwhd","group":"anarchy.gpte.redhat.com","kind":"anarchyruns"},"code":404}
```

**Comment by jkupferer** [comment]
Fixed
